# 如果需要指定外部配置文件java -jar xxx.jar --spring.config.location=配置文件路径
# 如果需要指定外部日志配置文件java -jar xxx.jar --logging.config=配置文件路径
server:
  port: 8099
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev